services:
  web:
    build:
      context: .
      dockerfile: docker/DockerFile
    container_name: document_manager_app
    env_file:
      - .env
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "7575:7575"
